USE Movies
GO
CREATE FULLTEXT CATALOG ftCatalog 
WITH ACCENT_SENSITIVITY = ON
AS DEFAULT
AUTHORIZATION dbo
GO

CREATE FULLTEXT INDEX ON movies(title)
KEY INDEX PK__movies ON (ftCatalog)
WITH (CHANGE_TRACKING AUTO)
GO
